// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2UFPQqv7TlqWo9DTSRMBI2QFWoRePc5I',
    appId: '1:539823018924:web:69c2926bf89340f12f2009',
    messagingSenderId: '539823018924',
    projectId: 'audio-player-app-ce0aa',
    authDomain: 'audio-player-app-ce0aa.firebaseapp.com',
    storageBucket: 'audio-player-app-ce0aa.appspot.com',
    measurementId: 'G-J3LJX2D5ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxAsvqRYnnK6BQO9S5HTBPjR0MkBWmF6g',
    appId: '1:539823018924:android:c75d245b3d61a9af2f2009',
    messagingSenderId: '539823018924',
    projectId: 'audio-player-app-ce0aa',
    storageBucket: 'audio-player-app-ce0aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMjCE9dujP2__Ycblvb2EzEUjQoLIGpag',
    appId: '1:539823018924:ios:5fe4d12a635ce3bd2f2009',
    messagingSenderId: '539823018924',
    projectId: 'audio-player-app-ce0aa',
    storageBucket: 'audio-player-app-ce0aa.appspot.com',
    androidClientId: '539823018924-9v6388u02j89km8lhiop1152ld0meheb.apps.googleusercontent.com',
    iosClientId: '539823018924-4l5vjakj2ia82lg4edkiol0bc0v8rij0.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioFlutterApp',
  );
}
